const whatIHaveHeard = [
  {
    year: "2020",
    aux: [
      { id: "73mygGW27LM", song: "Disappointed - Stormzy", num: 1 },
      { id: "912YaSKGdlo", song: "Still Disappointed - Stormzy", num: 2 },
      { id: "m4yFmRNcX3I", song: "Utrush Horas - Orchestra Baobab", num: 3 },
      { id: "IOnlmFN2xr4", song: "Aleb - Yasmine Hamdan", num: 4 },
      { id: "tEtlO4w_YDY", song: "Galbi - Soapkills", num: 5 },
      { id: "asMTYB-WcbE", song: "Gul l'Abi - Acid Arab", num: 6 },
      { id: "am93s9FKJ0U", song: "Ahwak Hiba - Zeid Hamdan", num: 7 },
      {
        id: "eQsAT0vIRaE",
        song: "Bad Company - A$AP Rocky, Blocboy JB",
        num: 8,
      },
      { id: "VwYWFWEwtxE", song: "Calling My Spirit - Kodak Black", num: 9 },
      { id: "kFJITWouJ8o", song: "Russian Cream - Key Glock", num: 10 },
      { id: "KqRJKMHwDlE", song: "Vingkor - Vic Crezèe, Faberyayo", num: 11 },
      {
        id: "_swivbEsD50",
        song: "Drank & Drugs - Lil Kleine, Ronnie Flex",
        num: 12,
      },
      { id: "es9-P1SOeHU", song: "Faceshopping - Sophie", num: 13 },
      { id: "3BsUwxbMzJc", song: "Interlaced - Les Gordon", num: 14 },
      { id: "I0RBmNPsAoI", song: "L.E.D - Les Gordon", num: 15 },
      {
        id: "5zpdl35gm1M",
        song: "Birds Fly By Night - Danger Incorporated",
        num: 16,
      },
      {
        id: "4i2ifGa5n0o",
        song: "Regular People (Conceit) - Pantera",
        num: 17,
      },
      {
        id: "B_HSa1dEL9s",
        song: "For Whom The Bell Tolls - Metallica",
        num: 18,
      },
      { id: "tzVJPgCn-Z8", song: "Kashmir - Led Zeppelin", num: 19 },
      { id: "KwJbqsZ_0KU", song: "Metallic Taste - Show Me The Body", num: 20 },
      { id: "KBVde75e4sU", song: "On the Beach - Neil Young", num: 21 },
      {
        id: "uX9k9aoX6gk",
        song: "Cortez the Killer - Neil Young, Crazy Horse",
        num: 22,
      },
      { id: "OJDfc3-OWvQ", song: "My Name Is Mud - Primus", num: 23 },
      { id: "LdpMpfp-J_I", song: "YYZ - Rush", num: 24 },
      {
        id: "IRTe7BzDbKQ",
        song: "Demon Time - Lil Yachty, Draft Day",
        num: 25,
      },
      { id: "u1KdGDEkj_U", song: "Baby - DakhaBrakha", num: 26 },
      { id: "h8mW3iA6O4M", song: "Split/Whole Time - Lil Yachty", num: 27 },
      { id: "7dWBrk9Z7B0", song: "Paulette - Balla Et Ses Balladins", num: 28 },
      { id: "nl_sl0wJANA", song: "King Kong - Babe Ruth", num: 29 },
      { id: "rAHcYCf_kGc", song: "Stayin True - Chris Travis", num: 30 },
      { id: "kk7t4LhKCw4", song: "Harlem River - Kevin Morby", num: 31 },
      { id: "KMJbJS6_8Ys", song: "Yes Indeed - Lil Baby, Drake", num: 32 },
      {
        id: "aT92TZhTI5I",
        song: "Décollage - Thievery Corporation, Loulou Ghelichkhani",
        num: 33,
      },
      { id: "6giKIu5jUvA", song: "Almeda - Solange", num: 34 },
      { id: "BQe6hTKX35o", song: "Mona Ki Ngi Xica - Bonga", num: 35 },
      { id: "Gqvi0zdN-tM", song: "Mamou - Franco, Madilu System", num: 36 },
      { id: "lY0mpRySPWk", song: "Golden Light - STRFKR", num: 37 },
      {
        id: "iWcQqWW3QCI",
        song: "This Night Has Opened My Eyes - The Smiths",
        num: 38,
      },
      {
        id: "K8R7zjJMIfU",
        song: "Since I've Been Loving You - Led Zeppelin",
        num: 39,
      },
      {
        id: "q2aKW7Cv9oU",
        song: "Charlotte's Thong - Connan Mockasin",
        num: 40,
      },
      { id: "zf99kdFw9b8", song: "Грустная Сука - IC3PEAK", num: 41 },
      { id: "mANTaSTDGv4", song: "Wild Life - Wings", num: 42 },
      { id: "YS1Tz6dzcjU", song: "You Shook Me - Led Zeppelin", num: 43 },
      { id: "tVCUAXOBF7w", song: "Hey - Pixies", num: 44 },
      { id: "w772GXG5LnE", song: "Dazed and Confused - Led Zeppelin", num: 45 },
      { id: "3Pt0V6K7WpM", song: "Feel It All Around - Washed Out", num: 46 },
      {
        id: "j3yE2NAdNKo",
        song: "Watermelon In Easter Hay - Frank Zappa",
        num: 47,
      },
      { id: "_3HKqmALMZo", song: "Flesh - Ghostemane", num: 48 },
      { id: "BbWBRnDK_AE", song: "Nude - Radiohead", num: 49 },
      { id: "qv3Kmq2TR9Y", song: "Cementerio Club - Pescado Rabioso", num: 50 },
      { id: "_3T8KznhThQ", song: "Raingurl - Yaeji", num: 51 },
      { id: "xZjqi4vUse8", song: "Charcoal Baby - Blood Orange", num: 52 },
      { id: "i_aYli_1iqs", song: "Money - Easy Star All-Stars", num: 53 },
      { id: "clyXBlYOHGQ", song: "One Spliff A Day - Billy Boyo", num: 54 },
      { id: "I7vOyMKp0rw", song: "Zim Zim - Billy Boyo", num: 55 },
      { id: "TQyfYyg4dZs", song: "Moonlight - Gaulin", num: 56 },
      { id: "_G1soKzXJUo", song: "All Night - Example", num: 57 },
      { id: "A3pJB4m713M", song: "Cooler Than Me - Lucky Luke", num: 58 },
      {
        id: "QIjKijhv1OU",
        song: "Slav King - DJ Blyatman, Life of Boris",
        num: 59,
      },
      {
        id: "5Mr_VkAXWZA",
        song: "All the Trees of the Field Will Clap Their Hands - Sufjan Stevens",
        num: 60,
      },
      {
        id: "IcvWGB5EqbA",
        song: "Husavik (My Hometown) - Will Ferrell, My Marianne",
        num: 61,
      },
      { id: "rtemrZ7-pj0", song: "Svefn-g-englar - Sigur Rós", num: 62 },
      { id: "KzyZZpi-QgM", song: "Manila Ice - Eyedress", num: 63 },
      {
        id: "C_weF3CN5I8",
        song: "Dark & Handsome - Blood Orange, Toro y Moi",
        num: 64,
      },
      { id: "kf1pVxHqSdI", song: "Just A Lover - Hayden James", num: 65 },
      { id: "sewad1OnOC8", song: "Audubon - $uicideboy$", num: 66 },
      {
        id: "ZI-hE4x4ZiQ",
        song: "Telephone Calls - A$AP Rocky, Tyler, The Creator",
        num: 67,
      },
      {
        id: "fdixQDPA2h0",
        song: "Moon (And It Went Like) - Kid Francescoli, Julia Minkin",
        num: 68,
      },
      { id: "FssULNGSZIA", song: "Pneuma - Tool", num: 69 },
      { id: "YXa-M2sYOOI", song: "Broke Boi - Playboi Carti", num: 70 },
      { id: "31j4DIpgY9U", song: "Mercury: Retrograde - Ghostemane", num: 71 },
      { id: "VNjyztyH168", song: "LooseScrew - BONES, Eddy Baker", num: 72 },
      { id: "hMqdjGcaRQ0", song: "Oxygen - BONES", num: 73 },
      { id: "lfBdGT4dn4E", song: "Two of Hearts - Stacey Q", num: 74 },
      { id: "HQliEKPg1Qk", song: "Boys - Lizzo", num: 75 },
      { id: "lpSvofs8O18", song: "Energia - Sofi Tukker", num: 76 },
      {
        id: "B1vDFDAWlQg",
        song: "Good Time Girl - Sofi Tukker, Charlie Barker",
        num: 77,
      },
      { id: "Ncr8TkdQUm8", song: "OG Beeper - A$AP Rocky", num: 78 },
      { id: "z3cvWow3y1w", song: "NOT MY BRO - Baby Keem", num: 79 },
      { id: "mavwHsZ2WeU", song: "STATS - Baby Keem", num: 80 },
      { id: "0eOIo9xib_8", song: "TakengOutTheTrash - BONES", num: 81 },
      {
        id: "ngFaNfsEBto",
        song: "Walzer Für Niemand - Sophie Hunger",
        num: 82,
      },
      {
        id: "-Zx0uIv0yyA",
        song: "Bones - Be Svendsen's Rodeo Rerub - Be Svendsen",
        num: 83,
      },
      { id: "kOhXk6c955Y", song: "F*ck Hoes - YROR?", num: 84 },
      { id: "Nl_Eo2QzqU4", song: "Rasputin - Boney M.", num: 85 },
      { id: "Ebdc4Px5cDo", song: "Daddy Cool - Boney M.", num: 86 },
      { id: "iaGjz4dtr3o", song: "Baianá - Bakermat", num: 87 },
      { id: "OE140zsQ08I", song: "Cradles - Sub Urban", num: 88 },
      { id: "Cj25UpcBDt0", song: "Changes - Faul & Wad, PNAU", num: 89 },
    ],
  },
  {
    year: "2021",
    aux: [
      {
        id: "UhBtXMOWPBM",
        song: "That Sea, That Gambler - Gregory Alan Isakov",
        num: 1,
      },
      { id: "djWzoxzE5u8", song: "Holland - Sufjan Stevens", num: 2 },
      { id: "uZHj4gFN4x8", song: "Berth - Gregor Alan Isakov", num: 3 },
      { id: "6EI8gxv13KQ", song: "Around - Noir, Hayze, Solomun", num: 4 },
      { id: "l12NQXmJ0JY", song: "Sunday - HNNY", num: 5 },
      { id: "1gdihQ_cnfQ", song: "Perdida - Biig Piig", num: 6 },
      { id: "6I44IYGyB_4", song: "Some Feeling - Mild Orange", num: 7 },
      {
        id: "HMCHHR8cw94",
        song: "Ti-de - Kokoroko",
        num: 8,
      },
      { id: "Osy54f7FQno", song: "LoveKills!!! - 9th Wonder", num: 9 },
      {
        id: "SNqL8X-VzG8",
        song: "Childs Play - SZA, Chance the Rapper",
        num: 10,
      },
      {
        id: "lG4HICGeQoo",
        song: "Come and See Me - PARTYNEXTDOOR, Drake",
        num: 11,
      },
      {
        id: "KkwAlhtMDRo",
        song: "Better Things - A$AP Rocky",
        num: 12,
      },
      {
        id: "xiOPvOBd8IA",
        song: "Cause We've Ended as Lovers - Jeff Beck",
        num: 13,
      },
      { id: "QUUfCmb-Mdo", song: "Wave - Rone, Noga Erez", num: 14 },
      { id: "XreMtQz6HkY", song: "4EVA - Lapalux, Talvi", num: 15 },
      {
        id: "lEnMb4m9lu0",
        song: "Milquetoast - Helmet",
        num: 16,
      },
      {
        id: "zaZ9mY8-NOU",
        song: "Mo Murder - Gangsta Pat",
        num: 17,
      },
      {
        id: "iUcAPCxrSQs",
        song: "Brujas - Princess Nokia",
        num: 18,
      },
      {
        id: "3W2jLb7AM3s",
        song: "Still Pimpin - Princess Loko, Tommy Wright III",
        num: 19,
      },
      {
        id: "LMtU1r6ndRI",
        song: "Die Ni**a Die - Tommy Wright III",
        num: 20,
      },
      {
        id: "P38JfibHLsM",
        song: "Claridad - Thievery Corporation, Natalia Clavier",
        num: 21,
      },
      {
        id: "Ktt_ZLE9cnQ",
        song: "This Land - Nu",
        num: 22,
      },
      {
        id: "R46UxgB92D8",
        song: "Rosa - Rainer Scheurenbrand, Jenna Conrad, Raúl Pereira",
        num: 23,
      },
      { id: "T9tiXQPLRXw", song: "Solitude - Karunesh", num: 24 },
      {
        id: "xL3PHmOBOBk",
        song: "Breathe - Bliss",
        num: 25,
      },
      { id: "ZBfF0TPrcVI", song: "Punjab - Karunesh", num: 26 },
      { id: "o_do-rZJL6I", song: "Whiplash'd - Xavier Wulf", num: 27 },
      {
        id: "EGveTSQbH30",
        song: "Bei Mir Bist Du Schoen - The Andrews Sisters",
        num: 28,
      },
      { id: "lcEkS9tcIjg", song: "Scotty Doesn't Know - Lustra", num: 29 },
      {
        id: "l4hOapJnHbg",
        song: "What Do They Know? - Mindless Self Indulgence",
        num: 30,
      },
      { id: "fTzgpec2bGc", song: "Psycho Pass - Xavier Wulf", num: 31 },
      { id: "2seCB54Bv-c", song: "Lay All Your Love On Me - ABBA", num: 32 },
      {
        id: "b7MUcj312a0",
        song: "Have You Ever Seen the Rain - Willie Nelson, Paula Nelson",
        num: 33,
      },
      { id: "qiipK0vpCTs", song: "Sweet Memories - CID, Kaskade", num: 34 },
      { id: "vgdeehM7Xb0", song: "Café Brasil - Croatia Squad", num: 35 },
      { id: "_iTT6-dK2Mk", song: "Cream - Radio Mix - Platinum Doug", num: 36 },
      { id: "7Ku011yByaM", song: "Loaded - Destructo, Yo Gotti", num: 37 },
      {
        id: "tcHBRMg2JN4",
        song: "Down in Mexico - The Coasters",
        num: 38,
      },
      {
        id: "lFREEtKRGr0",
        song: "I Want You - Chris Lake",
        num: 39,
      },
      {
        id: "j7n29J9PlTw",
        song: "You Ain't Gotta Bounce To This (Lean) - Black Caviar",
        num: 40,
      },
      { id: "nCH5AHqHqWI", song: "La Sirena Negra - Nu", num: 41 },
      {
        id: "BlyXi85Q1-8",
        song: "Who Loves The Sun - Jo.Ke, Acid Pauli",
        num: 42,
      },
      { id: "oBRLbDzZ_yk", song: "Jon Benet - 18 Carat Affair", num: 43 },
      {
        id: "pbRa6O-MG8s",
        song: "CD Player, Pt. III - death's dynamic shroud",
        num: 44,
      },
      { id: "B0b0kC7AhXY", song: "SPEEDBOAT - Denzel Curry", num: 45 },
      {
        id: "99rKoOSFcjw",
        song: "CharacterSelect (ВыборПерсонажа) - Bones",
        num: 46,
      },
      {
        id: "8rFd0efLhiE",
        song: "Enghave - Marco Egeberg",
        num: 47,
      },
      { id: "vhhkk69CxXc", song: "Break Apart - Bonobo, Rhye", num: 48 },
      { id: "iECixGaKVk4", song: "Broken Boy - Cage The Elephant", num: 49 },
      { id: "-pPEsRdm-Y4", song: "Juices - Parallel Dance Ensemble", num: 50 },
      {
        id: "f2ZLKfxqjVg",
        song: "I Am Your Mind (Part 2) - Roy Ayers",
        num: 51,
      },
      {
        id: "opeETnB8m8w",
        song: "Cigarette Daydreams - Cage The Elephant",
        num: 52,
      },
      {
        id: "CB74K0AR-gU",
        song: "Tall Cans In The Air - Transplants",
        num: 53,
      },
      { id: "KZnou4zthz4", song: "LITE SPOTS - KAYTRANADA", num: 54 },
      { id: "H-m42WC0NMk", song: "Μια φορά θυμάμαι - Αρλέτα", num: 55 },
      { id: "0qzzxXkClU4", song: "How Does It Feel - D. Savage", num: 56 },
      { id: "gsbZ3KX2CR8", song: "HUNNIDDOLLA - MadeinTYO", num: 57 },
      {
        id: "pq-yP7mb8UE",
        song: "I Will Possess Your Heart - Death Cab For Cutie",
        num: 58,
      },
      {
        id: "euZnnydVlGQ",
        song: "Грустный Дэнс - ЛУНА",
        num: 59,
      },
      {
        id: "CZ8_pMgd2Iw",
        song: "Спящая красавица - ЛУНА",
        num: 60,
      },
      {
        id: "LKdnxBH031I",
        song: "The Finishing - Stavroz",
        num: 61,
      },
      { id: "AVbklf_fIqE", song: "All My Friends - Seth XVI", num: 62 },
      {
        id: "I20Ym2pE0YE",
        song: "It's Only Music, Baby - Kid Francescoli, Julia Minkin",
        num: 63,
      },
      {
        id: "KBBf9SKJoB8",
        song: "Magic Carpet - Kyle Watson, MAY BBY",
        num: 64,
      },
      { id: "hed7IJ42HNI", song: "Next Song - DaBaby", num: 66 },
      {
        id: "w7yG1P2Nq_w",
        song: "Racked - Tommy Cash",
        num: 65,
      },
      {
        id: "1SuUe4HC0T4",
        song: "Crepuscolo Sul Mare - Piero Umiliani",
        num: 66,
      },
    ],
  },
];

module.exports = { whatIHaveHeard };
